enum BreedType {
	LabradorRetriever = 'labrador_retriever',
	GermanShepherd = 'german_shepherd',
	GoldenRetriever = 'golden_retriever',
	Bulldog = 'bulldog',
	Beagle = 'beagle',
	Poodle = 'poodle',
	Rottweiler = 'rottweiler',
	YorkshireTerrier = 'yorkshire_terrier',
	Dachshund = 'dachshund',
	Boxer = 'boxer',
	SiberianHusky = 'siberian_husky',
	FrenchBulldog = 'french_bulldog',
	ShihTzu = 'shih_tzu',
	DobermanPinscher = 'doberman_pinscher',
	CockerSpaniel = 'cocker_spaniel',
	Chihuahua = 'chihuahua',
	AustralianShepherd = 'australian_shepherd',
	Pomeranian = 'pomeranian',
	BichonFrise = 'bichon_frise',
	BorderCollie = 'border_collie',
	GreatDane = 'great_dane',
	MiniatureSchnauzer = 'miniature_schnauzer',
	SaintBernard = 'saint_bernard',
	BerneseMountainDog = 'bernese_mountain_dog',
	Maltese = 'maltese',
	EnglishSpringerSpaniel = 'english_springer_spaniel',
	Pekingese = 'pekingese',
	CavalierKingCharlesSpaniel = 'cavalier_king_charles_spaniel',
	Samoyed = 'samoyed',
	BulldogFrench = 'bulldog_french',
	Havanese = 'havanese',
	ShibaInu = 'shiba_inu',
	Akita = 'akita',
	ChowChow = 'chow_chow',
	Weimaraner = 'weimaraner',
	Collie = 'collie',
	Newfoundland = 'newfoundland',
	Persian = 'persian',
	MaineCoon = 'maine_coon',
	Ragdoll = 'ragdoll',
	BritishShorthair = 'british_shorthair',
	Siberian = 'siberian',
	Bengal = 'bengal',
	ScottishFold = 'scottish_fold',
	Sphynx = 'sphynx',
	Burmese = 'burmese',
	Birman = 'birman',
	Abyssinian = 'abyssinian',
	AmericanShorthair = 'american_shorthair',
	DevonRex = 'devon_rex',
	NorwegianForestCat = 'norwegian_forest_cat',
	RussianBlue = 'russian_blue',
	OrientalShorthair = 'oriental_shorthair',
	AmericanCurl = 'american_curl',
	EgyptianMau = 'egyptian_mau',
	Chartreux = 'chartreux',
	Manx = 'manx',
	CornishRex = 'cornish_rex',
	Tonkinese = 'tonkinese',
	SelkirkRex = 'selkirk_rex',
	Singapura = 'singapura',
	JapaneseBobtail = 'japanese_bobtail',
	Balinese = 'balinese',
	Somali = 'somali',
	TurkishAngora = 'turkish_angora',
}

enum PetSexType {
	Male = 'male',
	Female = 'female',
	PreferNotToSay = 'prefer_not_to_say',
}

enum SpeciesType {
	Dog = 'dog',
	Cat = 'cat',
}

enum UserRoleType {
	User = 'user',
	Client = 'client',
	Veterinarian = 'veterinarian',
	Admin = 'admin',
}

enum VeterinarySpecialization {
	GeneralPractitioner = 'general_practitioner',
	Surgeon = 'surgeon',
	Dermatologist = 'dermatologist',
	Cardiologist = 'cardiologist',
	Orthopedic = 'orthopedic',
	Dentist = 'dentist',
	Ophthalmologist = 'ophthalmologist',
	Oncologist = 'oncologist',
	InternalMedicine = 'internal_medicine',
	EmergencyAndCriticalCare = 'emergency_and_critical_care',
	Behaviorist = 'behaviorist',
}

enum AppointmentType {
	WellnessExam = 'wellness_exam',
	Vaccination = 'vaccination',
	SickVisit = 'sick_visit',
	FollowUp = 'follow_up',
	Surgery = 'surgery',
	DentalCleaning = 'dental_cleaning',
	Emergency = 'emergency',
	LaboratoryWork = 'laboratory_work',
	Imaging = 'imaging',
	Grooming = 'grooming',
	PhysicalTherapy = 'physical_therapy',
	BehavioralConsultation = 'behavioral_consultation',
	NutritionConsultation = 'nutrition_consultation',
	Euthanasia = 'euthanasia',
	NewPetConsultation = 'new_pet_consultation',
	SeniorPetCare = 'senior_pet_care',
	ParasiteControl = 'parasite_control',
	Microchipping = 'microchipping',
	MedicationRefill = 'medication_refill',
	SpayNeuter = 'spay_neuter',
	AllergyTesting = 'allergy_testing',
	OrthopedicEvaluation = 'orthopedic_evaluation',
	Ophthalmology = 'ophthalmology',
	Dermatology = 'dermatology',
	Cardiology = 'cardiology',
	Neurology = 'neurology',
	Oncology = 'oncology',
	HospiceCare = 'hospice_care',
	Telemedicine = 'telemedicine',
}

export {
	BreedType,
	PetSexType,
	SpeciesType,
	UserRoleType,
	VeterinarySpecialization,
	AppointmentType,
};
